### ISSUE TITLE
Maple tree output shows false in the middle of the newick format

### ISSUE THREAD

**Issue by josenikhid97** [NicolaDM/MAPLE#11]
Hello Nicola

I was running covid data using Maple under different models and the output of the tree newick file is showing " False " in the middle of the statements. but it is not showing under JC model and with the other models output it is showing. for a better understanding of my problem, i am also attaching a picture.
![false](https://user-images.githubusercontent.com/64956458/173341586-9cb54cde-9551-4638-af41-cab12485806e.png)

i didnt understand the reason behind it . if u could tell me any mistake i have done while running or is the mistake with the data ?

thank you

**Comment by NicolaDM** [comment]
Hi,

The problem was in a previous version of MAPLE which wrote "False" instead of "0.0" for some branch length when the option --binaryTree was not used.
The latest version of MAPLE (v0.1.1) will give you a binary tree by default, without the "False".
The difference between the models is probably because of the difference in MAPLE version used for the estimation.

Sorry for the problem, I am still ironing out the latest issues, please do let me know of any more issues!
