### ISSUE TITLE
Does Maple print log-likelihood values ?

### ISSUE THREAD

**Issue by josenikhid97** [NicolaDM/MAPLE#12]
Hello @NicolaDM  

I was able to run the tool successfully, but is there any flags to be added for printing the log-likelihood values because i cant see any log-likelihood values on the terminal,  all i can see is only the time taken for running the tool and some info about topology . is there any possible way to see the log-likelihood and also BIC values.

Best 
Jose

**Comment by NicolaDM** [comment]
Option --calculateLKfinalTree is the one you are looking for, which is available since the last few versions of MAPLE. This is not done by default because MAPLE doesn't normally calculate total tree likelihoods, so this is an extra step that requires some (usually not much) more run time.

Also note that currently branch lengths in MAPLE are not optimized as precisely as other software - we are working on efficient ways to do this that wouldn't affect the run time.

Regarding BIC, no, it's not currently calculated but it can of course be obtained from the likelihood I mentioned above.

**Comment by josenikhid97** [comment]
Thank you for the information and for the quick reply

**Comment by NicolaDM** [comment]
Regarding branch lengths, I have just uploaded a new version of MAPLE (0.1.4) that does a final proper branch length optimization step, so that now branch lengths will be more accurate.
Next I want to include the option to load a given tree in MAPLE and allow the option to calculate its likelihood - this should help compare the likelihoods of trees from different methods.

**Comment by NicolaDM** [comment]
This has now all been implemented.
