### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Bin-Ma** [NicolaDM/MAPLE#15]
Hi @NicolaDM,
I tried to construct the tree using MAPLEv0.1.6. In the end, the MAPLE showed there are something wrong.  I have no idea about that. Looking forward for your reply.

`Traceback (most recent call last):
  File "MAPLEv0.1.6.py", line 5804, in <module>
    improvement=traverseTreeToOptimizeBranchLengths(t1,mutMatrix,testing=testingBLen)
  File "MAPLEv0.1.6.py", line 3977, in traverseTreeToOptimizeBranchLengths
    bestLength=estimateBranchLengthWithDerivative(upVect,node.probVect,mutMatrix)
  File "MAPLEv0.1.6.py", line 3932, in estimateBranchLengthWithDerivative
    vUp=calculateDerivative(ais,tUp)
  File "MAPLEv0.1.6.py", line 3727, in calculateDerivative
    derivative+=1.0/(ai+t)

ZeroDivisionError: float division by zero`

This is the testing file.[test_file.txt](https://github.com/NicolaDM/MAPLE/files/9990943/test_file.txt)

**Comment by NicolaDM** [comment]
Hi @Bin-Ma ,
Some of the calculations in MAPLE are breaking down with your example, and the reason seems to be that your example has too diverged sequences. Even if I fixed this error message - which I should and will - the software would anyway be inaccurate and inefficient with such data. I am currently exploring exactly at what level of divergence it stops making sense using MAPLE, but for now, a rough rule of thumb is more or less that if the branches of the tree are typically long more than 0.01 then it's not worth using MAPLE (to give you an idea branches in highly-sampled SARS-CoV-2 trees are typically long less than 0.0001 ).

I posted today a new version of MAPLE, 0.1.9, that's more stable, but still won't work with this type of datasets. I will work to make at least the error messages more informative.

**Comment by NicolaDM** [comment]
I have now uploaded version 0.2.0, which solves this issue and limits the length of inferred branches to a maximum of 0.1 . Now MAPLE also prints a Warning when divergence or branch lengths are too high, recommending the use of a different software.
