### ISSUE TITLE
The tree output by maple has too many branch lengths of zero

### ISSUE THREAD

**Issue by fightyy** [NicolaDM/MAPLE#19]
I used 40,000 influenza HA nucleotide sequences with a sequence length of 987. Maple gave me a warning that there are sequences divergence exceeding 0.1. The final output tree has tens of thousands of branches with a length of zero. I don't know why. I'm not sure if such a result is credible

**Comment by NicolaDM** [comment]
The divergence from the reference, in itself, should not cause inaccuracy, just slowness. If however the branches of the tree are long, say >0.01 , this will cause inaccuracy.
Regarding the many branches of the tree with length 0, this in itself does not sound worrying to me. Maple is a maximum likelihood method, so for example if two sequences have no difference, unlike in Bayesian methods, the branches separating them will be inferred to be of length 0. Given that you have many sequence but a short sequence length, that sounds very possible. But you could double check how many sequences in your dataset have other sequences with a distance 0 from them, if you wanted to make sure.
Even if not many sequences have distance 0, you can still have branches inferred to be of length 0, for example if you have many or large polytomies/multifurcations, or if you have sequences that are identical to ancestral genomes in the tree. We see many of these in sars-cov-2 data.
If you do think this result is inaccurate or not credible, or if you want me to double check anyway, you can send me the alignment and results and I will check.

**Comment by leke-lyu** [comment]
Does MAPLE have the capability to retain polytomies in its phylogenetic analyses, rather than resolving them arbitrarily?

**Comment by NicolaDM** [comment]
Unlike many other methods, MAPLE does estimate and output polytomies, it represents them using branches of length 0. Are you asking if it would be possible to represent polymtomies in the MAPLE output tree differently, for example as 
(A:0.001,B:0.001,C:0.001);
Instead of the current format
((A:0.001,B:0.001):0.0,C:0.001);
?
I am currently using the latter format because it's more compatible with other software, that is, other phylogenetic visualization or inference methods will not crash when using this format for the input tree, while many of them do if one uses "explicit" polytomies like in the former example.
If this other format is indeed what you would like in the MAPLE output tree, let me know why, and I might try including this as an optional feature. Otherwise, polytomies in the current MAPLE output are already perfectly identifiable.

**Comment by NicolaDM** [comment]
I see you opened a different issue with the same request, I will close this one and reply to the other one.
