### ISSUE TITLE
do NOT resolve polytomies.

### ISSUE THREAD

**Issue by leke-lyu** [NicolaDM/MAPLE#21]
I am using the resulting MAPLE tree as input to infer timing using the BEAST module, which is designed for analyzing large phylogenetic datasets (https://beast.community/thorney_beast). This awesome module allows for the sampling of multiple possible resolutions. Can MAPLE retain these polytomies in the resulting phylogeny?

**Comment by NicolaDM** [comment]
Unlike many other methods, MAPLE does estimate and output polytomies, it represents them using branches of length 0. Are you asking if it would be possible to represent polymtomies in the MAPLE output tree differently, for example as
(A:0.001,B:0.001,C:0.001);
Instead of the current format
((A:0.001,B:0.001):0.0,C:0.001);
?
I am currently using the latter format because it's more compatible with other software, that is, other phylogenetic visualization or inference methods will not crash when using this format for the input tree, while many of them do if one uses "explicit" polytomies like in the former example.
If this other format is indeed what you would like in the MAPLE output tree, let me know, better if you give me an example of the kind of format that you would need for running Thorney BEAST. I will then try to include this as an optional output format.

**Comment by leke-lyu** [comment]
Hi Nicola,
A format like "((A:0.001,B:0.001):0.0,C:0.001);" will be viewed as fully resolved in thorney_beast, so this format will not sample other possible resolutions. So, yes, I prefer the format like "(A:0.001,B:0.001,C:0.001);".
Here is an example file,
[1K_SARS-CoV-2.nexus.zip](https://github.com/NicolaDM/MAPLE/files/13336629/1K_SARS-CoV-2.nexus.zip)

**Comment by NicolaDM** [comment]
Hi,
I have now implemented this, you will just need to use option "--nonBinaryTree" with the newest version of MAPLE (v0.3.6) that I have just uploaded. Please let me know if there are any issues.

**Comment by leke-lyu** [comment]
Hi Nicola,
Thanks for your effort on this issue. The resulting tree looks great. I passed the tree into the Thorney BEAST and it performed so much better.

**Comment by NicolaDM** [comment]
I'm glad it helped!
