### ISSUE TITLE
Q: internal ancestral reconstruction, e.g. number of mutations

### ISSUE THREAD

**Issue by sanerum** [NicolaDM/MAPLE#22]
How can one view and analyze the internal ancestral reconstruction of  tree created by MAPLE, e.g. to define the number and type of mutations.?
Thank you.

**Comment by NicolaDM** [comment]
Hi! 
To estimate mutation events in MAPLE, you can use option "--estimateMAT", available in later versions of MAPLE.
The nexus tree output will then contain the estimated tree annotated with the mutation events. This can be visualized with taxonium https://taxonium.org/  (remember to select option "nexus tree" in taxonium).
MAPLE will also create a tsv file containing the estimated mutations and other features of the tree. This tsv can also be used as input for taxonium instead of the nexus tree, or it can be analyzed on its own, for example for counting mutation events of different types.

Let me know if you have other questions.

Nicola

**Comment by sanerum** [comment]
Thank you very much for the fast and useful reply. I will look at this feature and likely use the TSV format.

 

Urs Saner

----------------------------------------

 

Von: NicolaDM ***@***.***> 
Gesendet: Mittwoch, 10. Januar 2024 17:16
An: NicolaDM/MAPLE ***@***.***>
Cc: sanerum ***@***.***>; Author ***@***.***>
Betreff: Re: [NicolaDM/MAPLE] Q: internal ancestral reconstruction, e.g. number of mutations (Issue #22)

 

Hi!
To estimate mutation events in MAPLE, you can use option "--estimateMAT", available in later versions of MAPLE.
The nexus tree output will then contain the estimated tree annotated with the mutation events. This can be visualized with taxonium https://taxonium.org/ (remember to select option "nexus tree" in taxonium).
MAPLE will also create a tsv file containing the estimated mutations and other features of the tree. This tsv can also be used as input for taxonium instead of the nexus tree, or it can be analyzed on its own, for example for counting mutation events of different types.

Let me know if you have other questions.

Nicola

**Comment by NicolaDM** [comment]
Great!
