### ISSUE TITLE
inconsistency in management of multifasta from createMapleFile.py

### ISSUE THREAD

**Issue by PCas95** [NicolaDM/MAPLE#25]
Hello, I'm experiencing an unexpected behaviour when trying to produce the Maple file through `createMapleFile.py`. I was wondering if someone could help me figuring out how to circumvent this.

If I understand the guide correctly, the flow requires: `obtain multi-alignment fasta ->  produce a maple file with createMapleFile.py -> run maple`.

I am attempting to create a Maple file from a multi-alignment fasta file produced with `mafft`. Passing the argument `--reference` to `createMapleFile.py` will raise the error below:

```sh
$ python3.12 createMapleFile.py --path input/ --reference NC_045512.2.fasta --fasta aligned.fa --output maple_file --overwrite
Ref genome length: 29903
Seq NC_045512_2_Severe_acute_respiratory_syndrome_coronavirus_2_isolate_Wuhan-Hu-1_complete_genome has length 29925 while reference is 29903
```

> (`NC_045512_2_Severe_acute_respiratory_syndrome_coronavirus_2_isolate_Wuhan-Hu-1_complete_genome` is `NC_045512.2.fasta`'s header and thus also present for the corresponding sequence in the multi-alignment file).

However, I do expect the multi alignment tool to insert gaps in the sequences, to ensure they all have the same length when aligned.
This behaviour of `createMapleFile.py` will actually prevent me from manually selecting the desired sequence as reference.

Of course the issue is not present when I run the tool without the `--reference` argument, but in that case I'm not able to define the reference myself.

Do you have recommendations on running  `createMapleFile.py` and/or should I use a specific multi-alignment tool with your software?
Is this behaviour expected for `createMapleFile.py`?

If I can't produce a Maple file, I can't run Maple, so any help would be greatly appreciated. Thank you for your support.

**Comment by NicolaDM** [comment]
Hi Pierluigi,

My recommendation is to run the script without the option --reference. This way the script will create its own consensus reference, and it will make MAPLE a little bit faster. I don't know your reason for wanting to use your own reference: the reference in MAPLE should not affect estimates, only marginally affect the time and memory demand.

For why the script is giving you the error, the reason is that typically the input are sequences aligned to the reference, so that each sequence has the same length as the reference. That said, you can still use a general multiple sequence alignment as input, but the reference would have to be the same length as the alignment and of course be representative of the alignment. Not using option --reference will effectively achieve this by creating the position-wise consensus of the alignment and using it as reference. If you really want to use your own reference, then my suggestion would be to include the reference in the multiple sequence alignment (as part of the sequences being aligned), and then use the row corresponding to the reference in the multiple sequence alignment as a reference for MAPLE. However, the gap characters "-" in this reference would have to be replaced by nucleotide characters, and I would again recommend for this to use the consensus nucleotide of the corresponding alignment columns (what the script does automatically for you).

**Comment by PCas95** [comment]
Hi Nicola,

Thank you for your answer. The reason why I wanted to specify my own reference is that I was facing issues running `MAPLEv0.6.11.py` on the file produced with `createMapleFile.py`, when the `--reference` option was not in use. However I solved that issue and now running without `--reference` as you suggested also works.

Thank you again for your help
